name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
        target: [cryptodll, parseflashfile, seednkey_sls]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (x86)
        if: matrix.arch == 'x86'
        run: cmake --preset x86

      - name: Configure (x64)
        if: matrix.arch == 'x64'
        run: cmake --preset x64

      - name: Build (x86)
        if: matrix.arch == 'x86'
        run: cmake --build --preset x86-release --target ${{ matrix.target }}

      - name: Build (x64)
        if: matrix.arch == 'x64'
        run: cmake --build --preset x64-release --target ${{ matrix.target }}
